version: '3.8'

services:
  pgsql:
    image: postgres:15-alpine
    container_name: mhas_pgsql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mh_assaodah
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - mhas_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  mhas_pgdata:
